import { Language } from "./Language";
import { ContentDescriptor } from "./ContentDescriptor";
import { Images } from "./Images";

export interface Show {
  id: number,
  dtAccounting: Date,
  dttmShowStart: Date,
  dttmShowStartUTC: Date,
  dttmShowEnd: Date,
  dttmShowEndUTC: Date,
  showSalesStartTime: Date,
  showSalesStartTimeUTC: Date,
  showSalesEndTime: Date,
  showSalesEndTimeUTC: Date,
  showReservationStartTime: Date,
  showReservationStartTimeUTC: Date,
  showReservationEndTime: Date,
  showReservationEndTimeUTC: Date,
  eventId: number,
  title: string,
  originalTitle: string,
  productionYear: number,
  lengthInMinutes: number,
  dtLocalRelease: Date,
  rating: number,
  ratingLabel: number,
  ratingImageURL: string,
  eventType: string,
  genres: string,
  theatreId: number,
  theatreAuditriumId: number,
  theatre: string,
  theatreAuditorium: string,
  theatreAndAuditorium: string,
  presentationMethodAndLanguage: string,
  presentationMethod: string,
  eventSeries: string,
  showUrl: string,
  eventUrl: string,
  spokenLanguage: Language,
  subtitleLanguage1: Language,
  subtitleLanguage2: Language,
  images: Images,
  contentDescriptors: ContentDescriptor[] | ContentDescriptor | null,
}