import { Language, LanguageXml2Js } from "./Language";
import { ContentDescriptor } from "./ContentDescriptor";
import { Images, ImagesXml2Js } from "./Images";

export interface Show {
  id: number,
  dtAccounting: string,
  dttmShowStart: string,
  dttmShowStartUTC: string,
  dttmShowEnd: string,
  dttmShowEndUTC: string,
  showSalesStartTime: string,
  showSalesStartTimeUTC: string,
  showSalesEndTime: string,
  showSalesEndTimeUTC: string,
  showReservationStartTime: string,
  showReservationStartTimeUTC: string,
  showReservationEndTime: string,
  showReservationEndTimeUTC: string,
  eventId: number,
  title: string,
  originalTitle: string,
  productionYear: number,
  lengthInMinutes: number,
  dtLocalRelease: string,
  rating: number,
  ratingLabel: number,
  ratingImageUrl: string,
  eventType: string,
  genres: string,
  theatreId: number,
  theatreAuditriumId: number,
  theatre: string,
  theatreAuditorium: string,
  theatreAndAuditorium: string,
  presentationMethodAndLanguage: string,
  presentationMethod: string,
  eventSeries: string,
  showUrl: string,
  eventUrl: string,
  spokenLanguage?: Language,
  subtitleLanguage1: Language,
  subtitleLanguage2?: Language,
  images: Images,
  contentDescriptors: ContentDescriptor[] | ContentDescriptor | null,
}

export interface ShowXml2Js {
  ID: [number],
  dtAccounting: [string],
  dttmShowStart: [string],
  dttmShowStartUTC: [string],
  dttmShowEnd: [string],
  dttmShowEndUTC: [string],
  ShowSalesStartTime: [string],
  ShowSalesStartTimeUTC: [string],
  ShowSalesEndTime: [string],
  ShowSalesEndTimeUTC: [string],
  ShowReservationStartTime: [string],
  ShowReservationStartTimeUTC: [string],
  ShowReservationEndTime: [string],
  ShowReservationEndTimeUTC: [string],
  EventID: [number],
  Title: [string],
  OriginalTitle: [string],
  ProductionYear: [number],
  LengthInMinutes: [number],
  dtLocalRelease: [string],
  Rating: [number],
  RatingLabel: [number],
  RatingImageUrl: [string],
  EventType: [string],
  Genres: [string],
  TheatreID: [number],
  TheatreAuditriumID: [number],
  Theatre: [string],
  TheatreAuditorium: [string],
  TheatreAndAuditorium: [string],
  PresentationMethodAndLanguage: [string],
  PresentationMethod: [string],
  EventSeries: [string],
  ShowURL: [string],
  EventURL: [string],
  SpokenLanguage?: [LanguageXml2Js],
  SubtitleLanguage1: [LanguageXml2Js],
  SubtitleLanguage2?: [LanguageXml2Js],
  Images: ImagesXml2Js,
  ContentDescriptors: ContentDescriptor[] | ContentDescriptor | null,
}