interface Config {
  _baseURL: string,
  _defaultArea: string,
  _numberOfDays: number,
  _downloadDir: string,
  _areaXmlFilename: string,
  _scheduleDatesXmlFilename: string,
  _scheduleXmlFilename: string,
  baseURL: string,
  areasUrl: string,
  scheduleDatesUrl?: string,
  scheduleUrl?: string,
  eventsUrl?: string,
  newsUrl?: string,
  newsCategoriesUrl?: string,
  defaultArea: string,
  numberOfDays: number,
  downloadDir?: string,
  areaXmlFilename: string,
  scheduleDatesXmlFilename: string,
  scheduleXmlFilename: string,
}

export let config: Config = {
  _baseURL: 'https://www.finnkino.fi/xml',
  _defaultArea: '1046',
  _numberOfDays: 1,
  _downloadDir: './downloads',
  _areaXmlFilename: 'Areas.xml',
  _scheduleDatesXmlFilename: "ScheduleDates.xml",
  _scheduleXmlFilename: "Schedule.xml",
  get baseURL() { return this._baseURL },
  set baseURL(value) {
    this._baseURL = value;
  },
  get areasUrl() { return this._baseURL + '/TheatreAreas/' },
  get scheduleDatesUrl() { return this._baseURL + '/ScheduleDates/' },
  get scheduleUrl() { return this._baseURL + '/Schedule/' },
  get eventsUrl() { return this._baseURL + '/Events/' },
  get newsUrl() { return this._baseURL + '/News/' },
  get newsCategoriesUrl() { return this._baseURL + '/NewsCategories/' },
  get defaultArea() { return this._defaultArea},
  set defaultArea(value) { this._defaultArea = value },
  get numberOfDays() { return this._numberOfDays },
  set numberOfDays(value: number) { this._numberOfDays = value },
  get downloadDir() { return this._downloadDir },
  set downloadDir(value: string) { this._downloadDir = value },
  get areaXmlFilename() { return this._areaXmlFilename },
  set areaXmlFilename(value: string) { this._areaXmlFilename = value },
  get scheduleDatesXmlFilename() { return this._scheduleDatesXmlFilename },
  set scheduleDatesXmlFilename(value: string) { this._scheduleDatesXmlFilename = value },
  get scheduleXmlFilename() { return this._scheduleXmlFilename },
  set scheduleXmlFilename(value: string) { this._scheduleXmlFilename = value },
}
